var oscarsDataset = [
  {
    "Year": 1990,
    "Picture": "Dances with Wolves",
    "Studio": "Orion",
    "BoxOffice": 184208848,
    "Nominations": 12,
    "Wins": 7,
    "Release Date": "11-sep",
    "PosterURL": "<img src='https://movieposteraddict.files.wordpress.com/2008/02/mpadanceswithwolvesposterb.jpg' width=140 height=200>",
    "Budget": 19000000,
    "ratingIMDB": 8,
    "duration": 181,
    "genre1": "Adventure",
    "genre2": "Drama",
    "metacritic": 72,
    "synopsis": "Lt. John Dunbar exiled to a remote western Civil War outpost befriends wolves and Indians making him an intolerable aberration in the military."
  },
  {
    "Year": 1991,
    "Picture": "The Silence of the Lambs",
    "Studio": "Orion",
    "BoxOffice": 130742922,
    "Nominations": 7,
    "Wins": 5,
    "Release Date": "feb-14",
    "PosterURL": "<img src='https://movieposteraddict.files.wordpress.com/2008/02/mpasilenceofthelambsposter.jpg' width=140 height=200>",
    "Budget": 19000000,
    "ratingIMDB": 8.6,
    "duration": 118,
    "genre1": "Crime",
    "genre2": "Drama",
    "metacritic": 84,
    "synopsis": "A young F.B.I. cadet must confide in an incarcerated and manipulative killer to receive his help on catching another serial killer who skins his victims."
  },
  {
    "Year": 1992,
    "Picture": "Unforgiven",
    "Studio": "Warner Bros.",
    "BoxOffice": 101157447,
    "Nominations": 9,
    "Wins": 4,
    "Release Date": "08-jul",
    "PosterURL": "<img src='https://movieposteraddict.files.wordpress.com/2008/02/mpaunforgivenposterb.jpg' width=140 height=200>",
    "Budget": 14400000,
    "ratingIMDB": 8.3,
    "duration": 131,
    "genre1": "Western",
    "genre2": "",
    "metacritic": 82,
    "synopsis": "Retired Old West gunslinger William Munny reluctantly takes on one last job with the help of his old partner and a young man."
  },
  {
    "Year": 1993,
    "Picture": "Schindler's List",
    "Studio": "Universal",
    "BoxOffice": 96065768,
    "Nominations": 12,
    "Wins": 7,
    "Release Date": "dic-15",
    "PosterURL": "<img src='http://img.moviepostershop.com/schindlers-list-movie-poster-1993-1020189480.jpg' width=140 height=200>",
    "Budget": 25000000,
    "ratingIMDB": 8.9,
    "duration": 195,
    "genre1": "Biography",
    "genre2": "Drama",
    "metacritic": 93,
    "synopsis": "In Poland during World War II Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis."
    },
  {
    "Year": 1994,
    "Picture": "Forrest Gump",
    "Studio": "Paramount",
    "BoxOffice": 329694499,
    "Nominations": 13,
    "Wins": 6,
    "Release Date": "07-jun",
    "PosterURL": "<img src='http://images.fanpop.com/images/image_uploads/Forrest-Gump-Movie-Poster-forrest-gump-509923_288_400.jpg' width=140 height=200>",
    "Budget": 55000000,
    "ratingIMDB": 8.8,
    "duration": 142,
    "genre1": "Drama",
    "genre2": "Romance",
    "metacritic": 82,
    "synopsis": "Forrest Gump while not intelligent has accidentally been present at many historic moments but his true love Jenny Curran eludes him."
  },
  {
    "Year": 1995,
    "Picture": "Braveheart",
    "Studio": "Paramount",
    "BoxOffice": 75609945,
    "Nominations": 10,
    "Wins": 5,
    "Release Date": "may-24",
    "PosterURL": "<img src='https://501mustseemoviesproject.files.wordpress.com/2014/06/braveheartposter.jpg' width=140 height=200>",
    "Budget": 53000000,
    "ratingIMDB": 8.4,
    "duration": 178,
    "genre1": "Biography",
    "genre2": "Drama",
    "metacritic": 68,
    "synopsis": "When his secret bride is executed for assaulting an English soldier who tried to rape her William Wallace begins a revolt against King Edward I of England."
  },
  {
    "Year": 1996,
    "Picture": "The English Patient",
    "Studio": "Miramax.",
    "BoxOffice": 78676425,
    "Nominations": 12,
    "Wins": 9,
    "Release Date": "nov-15",
    "PosterURL": "<img src='https://www.goldenglobes.com/sites/default/files/articles/cover_images/1997-the-english-patient.jpg' width=140 height=200>",
    "Budget": 27000000,
    "ratingIMDB": 7.4,
    "duration": 162,
    "genre1": "Drama",
    "genre2": "Romance",
    "metacritic": 87,
    "synopsis": "At the close of WWII a young nurse tends to a badly-burned plane crash victim. His past is shown in flashbacks revealing an involvement in a fateful love affair."
  },
  {
    "Year": 1997,
    "Picture": "Titanic",
    "Studio": "Paramount",
    "BoxOffice": 600788188,
    "Nominations": 14,
    "Wins": 11,
    "Release Date": "dic-19",
    "PosterURL": "<img src='https://movieposteraddict.files.wordpress.com/2008/02/mpatitanicposterb.jpg' width=140 height=200>",
    "Budget": 200000000,
    "ratingIMDB": 7.7,
    "duration": 194,
    "genre1": "Drama",
    "genre2": "Romance",
    "metacritic": 74,
    "synopsis": "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious ill-fated R.M.S. Titanic."
  },
  {
    "Year": 1998,
    "Picture": "Shakespeare in Love",
    "Studio": "Miramax.",
    "BoxOffice": 100317794,
    "Nominations": 13,
    "Wins": 7,
    "Release Date": "12-nov",
    "PosterURL": "<img src='https://movieposteraddict.files.wordpress.com/2008/02/mpashakespeareiNew Line Cinemaoveposterb.jpg' width=140 height=200>",
    "Budget": 25000000,
    "ratingIMDB": 7.2,
    "duration": 123,
    "genre1": "Comedy",
    "genre2": "Drama",
    "metacritic": 87,
    "synopsis": "A young Shakespeare out of ideas and short of cash meets his ideal woman and is inspired to write one of his most famous plays."
  },
  {
    "Year": 1999,
    "Picture": "American Beauty",
    "Studio": "DreamWorks",
    "BoxOffice": 130096601,
    "Nominations": 8,
    "Wins": 5,
    "Release Date": "sep-15",
    "PosterURL": "<img src='https://movieposteraddict.files.wordpress.com/2008/02/mpaamericanbeautyposterb.jpg' width=140 height=200>",
    "Budget": 15000000,
    "ratingIMDB": 8.4,
    "duration": 122,
    "genre1": "Drama",
    "genre2": "Romance",
    "metacritic": 86,
    "synopsis": "A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughters best friend."
  },
 
  {
    "Year": 2000,
    "Picture": "Gladiator",
    "Studio": "DreamWorks",
    "BoxOffice": 187705427,
    "Nominations": 12,
    "Wins": 5,
    "Release Date": "05-may",
    "PosterURL": "<img src='https://movieposteraddict.files.wordpress.com/2008/02/mpagladiatorposterb.jpg' width=140 height=200>",
    "Budget": 103000000,
    "ratingIMDB": 8.5,
    "duration": 155,
    "genre1": "Action",
    "genre2": "Drama",
    "metacritic": 64,
    "synopsis": "When a Roman general is betrayed and his family murdered by an emperors corrupt son he comes to Rome as a gladiator to seek revenge."
  },
  {
    "Year": 2001,
    "Picture": "A Beautiful Mind",
    "Studio": "Universal",
    "BoxOffice": 170742341,
    "Nominations": 8,
    "Wins": 4,
    "Release Date": "dic-21",
    "PosterURL": "<img src='https://trastos.files.wordpress.com/2008/09/poster-a-beautiful-mind1.jpg' width=140 height=200>",
    "Budget": 60000000,
    "ratingIMDB": 8.2,
    "duration": 135,
    "genre1": "Biography",
    "genre2": "Drama",
    "metacritic": 72,
    "synopsis": "After a brilliant but asocial mathematician John Nash accepts secret work in cryptography his life takes a turn for the nightmarish."
  },
  {
    "Year": 2002,
    "Picture": "Chicago",
    "Studio": "Miramax.",
    "BoxOffice": 170687518,
    "Nominations": 13,
    "Wins": 6,
    "Release Date": "dic-27",
    "PosterURL": "<img src='https://movieposteraddict.files.wordpress.com/2008/02/mpachicagoposterb.jpg' width=140 height=200>",
    "Budget": 45000000,
    "ratingIMDB": 7.2,
    "duration": 113,
    "genre1": "Comedy",
    "genre2": "Crime",
    "metacritic": 82,
    "synopsis": "Murderesses Velma Kelly and Roxie Hart find themselves on death row together and fight for the fame that will keep them from the gallows in 1920s Chicago."
  },
  {
    "Year": 2003,
    "Picture": "The Lord of the Rings: The Return of the King",
    "Studio": "New Line Cinema",
    "BoxOffice": 377027325,
    "Nominations": 11,
    "Wins": 11,
    "Release Date": "dic-17",
    "PosterURL": "<img src='https://movieposteraddict.files.wordpress.com/2008/02/mpareturnofthekingposterb.jpg' width=140 height=200>",
    "Budget": 94000000,
    "ratingIMDB": 8.9,
    "duration": 201,
    "genre1": "Adventure",
    "genre2": "Drama",
    "metacritic": 94,
    "synopsis": "Gandalf and Aragorn lead the World of Men against Saurons army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring."
  },
  {
    "Year": 2004,
    "Picture": "Million Dollar Baby",
    "Studio": "Warner Bros.",
    "BoxOffice": 100492203,
    "Nominations": 7,
    "Wins": 4,
    "Release Date": "dic-15",
    "PosterURL": "<img src='https://movieposteraddict.files.wordpress.com/2008/02/mpamilliondollarbabyposterb.jpg' width=140 height=200>",
    "Budget": 30000000,
    "ratingIMDB": 8.1,
    "duration": 132,
    "genre1": "Drama",
    "genre2": "Sport",
    "metacritic": 86,
    "synopsis": "A determined woman works with a hardened boxing trainer to become a professional."
  },
  {
    "Year": 2005,
    "Picture": "Crash",
    "Studio": "LionsGate",
    "BoxOffice": 54580300,
    "Nominations": 6,
    "Wins": 3,
    "Release Date": "05-jun",
    "PosterURL": "<img src='https://movieposteraddict.files.wordpress.com/2008/02/mpacrashposterb.jpg' width=140 height=200>",
    "Budget": 6500000,
    "ratingIMDB": 7.9,
    "duration": 112,
    "genre1": "Drama",
    "genre2": "",
    "metacritic": 69,
    "synopsis": "Los Angeles citizens with vastly separate lives collide in interweaving stories of race loss and redemption."
  },
  {
    "Year": 2006,
    "Picture": "The Departed",
    "Studio": "Warner Bros.",
    "BoxOffice": 132384315,
    "Nominations": 5,
    "Wins": 4,
    "Release Date": "10-jun",
    "PosterURL": "<img src='https://movieposteraddict.files.wordpress.com/2008/02/mpathedepartedposterb.jpg' width=140 height=200>",
    "Budget": 90000000,
    "ratingIMDB": 8.5,
    "duration": 151,
    "genre1": "Crime",
    "genre2": "Drama",
    "metacritic": 86,
    "synopsis": "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston."
  },
  {
    "Year": 2007,
    "Picture": "No Country for Old Men",
    "Studio": "Miramax.",
    "BoxOffice": 74283625,
    "Nominations": 8,
    "Wins": 4,
    "Release Date": "11-sep",
    "PosterURL": "<img src='http://img.moviepostershop.com/no-country-for-old-men-movie-poster-2007-1020402476.jpg' width=140 height=200>",
    "Budget": 25000000,
    "ratingIMDB": 8.1,
    "duration": 122,
    "genre1": "Crime",
    "genre2": "Drama",
    "metacritic": 91,
    "synopsis": "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande."
  },
  {
    "Year": 2008,
    "Picture": "Slumdog Millionaire",
    "Studio": "Fox Searchlight",
    "BoxOffice": 141319928,
    "Nominations": 10,
    "Wins": 8,
    "Release Date": "11-dic",
    "PosterURL": "<img src='https://movieposteraddict.files.wordpress.com/2009/02/mpaslumdogmillionaireposterb.jpg' width=140 height=200>",
    "Budget": 15000000,
    "ratingIMDB": 8,
    "duration": 120,
    "genre1": "Drama",
    "genre2": "Romance",
    "metacritic": 86,
    "synopsis": "A Mumbai teen reflects on his upbringing in the slums when he is accused of cheating on the Indian Version of \"Who Wants to be a Millionaire?\""
  },
  {
    "Year": 2009,
    "Picture": "The Hurt Locker",
    "Studio": "Summit entertainment",
    "BoxOffice": 17017811,
    "Nominations": 9,
    "Wins": 6,
    "Release Date": "jun-26",
    "PosterURL": "<img src='https://movieposteraddict.files.wordpress.com/2008/02/mpathehurtlockerposterb.jpg' width=140 height=200>",
    "Budget": 11000000,
    "ratingIMDB": 7.6,
    "duration": 131,
    "genre1": "Drama",
    "genre2": "History",
    "metacritic": 94,
    "synopsis": "During the Iraq War a Sergeant recently assigned to an army bomb squad is put at odds with his squad mates due to his maverick way of handling his work."
  },
  {
    "Year": 2010,
    "Picture": "The King's Speech",
    "Studio": "Weinstein",
    "BoxOffice": 135453143,
    "Nominations": 12,
    "Wins": 4,
    "Release Date": "nov-26",
    "PosterURL": "<img src='https://movieposteraddict.files.wordpress.com/2008/02/mpathekingsspeechb.jpg' width=140 height=200>",
    "Budget": 15000000,
    "ratingIMDB": 8,
    "duration": 118,
    "genre1": "Biography",
    "genre2": "Drama",
    "metacritic": 88,
    "synopsis": "The story of King George VI of the United Kingdom of Great Britain and Northern Ireland his impromptu ascension to the throne and the speech therapist who helped the unsure monarch become worthy of it."
 
  },
  {
    "Year": 2011,
    "Picture": "The Artist",
    "Studio": "Weinstein",
    "BoxOffice": 44671682,
    "Nominations": 10,
    "Wins": 5,
    "Release Date": "nov-25",
    "PosterURL": "<img src='https://movieposteraddict.files.wordpress.com/2012/02/mpatheartistoscar-b.jpg' width=140 height=200>",
    "Budget": 15000000,
    "ratingIMDB": 8,
    "duration": 100,
    "genre1": "Comedy",
    "genre2": "Drama",
    "metacritic": 89,
    "synopsis": "A silent movie star meets a young dancer but the arrival of talking pictures sends their careers in opposite directions."
  },
  {
    "Year": 2012,
    "Picture": "Argo",
    "Studio": "Warner Bros.",
    "BoxOffice": 136025503,
    "Nominations": 7,
    "Wins": 3,
    "Release Date": "10-dic",
    "PosterURL": "<img src='http://www.demasiadocine.com/wp-content/uploads/2012/09/argo-afiche.jpg' width=140 height=200>",
    "Budget": 44500000,
    "ratingIMDB": 7.8,
    "duration": 120,
    "genre1": "Biography",
    "genre2": "Drama",
    "metacritic": 86,
    "synopsis": "Acting under the cover of a Hollywood producer scouting a location for a science fiction film a CIA agent launches a dangerous operation to rescue six Americans in Tehran during the U.S. hostage crisis in Iran in 1980."
  },
  {
    "Year": 2013,
    "Picture": "12 Years a Slave",
    "Studio": "Fox Searchlight",
    "BoxOffice": 56671993,
    "Nominations": 9,
    "Wins": 3,
    "Release Date": "oct-18",
    "PosterURL": "<img src='https://pre00.deviantart.net/f34b/th/pre/i/2014/066/2/6/don_t_just_survive___12_years_a_slave_poster_by_disgorgeapocalypse-d79a20g.png' width=140 height=200>",
    "Budget": 17100000,
    "ratingIMDB": 8.1,
    "duration": 134,
    "genre1": "Biography",
    "genre2": "Drama",
    "metacritic": 97,
    "synopsis": "In the antebellum United States Solomon Northup a free black man from upstate New York is abducted and sold into slavery."
  },
  {
    "Year": 2014,
    "Picture": "Birdman",
    "Studio": "Fox Searchlight",
    "BoxOffice": 42340598,
    "Nominations": 9,
    "Wins": 4,
    "Release Date": "oct-17",
    "PosterURL": "<img src='http://img.moviepostershop.com/birdman-movie-poster-2014-1010771721.jpg' width=140 height=200>",
    "Budget": 18000000,
    "ratingIMDB": 7.8,
    "duration": 119,
    "genre1": "Comedy",
    "genre2": "Drama",
    "metacritic": 88,
    "synopsis": "Illustrated upon the progress of his latest Broadway play a former popular actors struggle to cope with his current life as a wasted actor is shown."
  },
  {
    "Year": 2015,
    "Picture": "Spotlight",
    "Studio": "ORF",
    "BoxOffice": 45055776,
    "Nominations": 6,
    "Wins": 2,
    "Release Date": "11-jun",
    "PosterURL": "<img src='http://es.web.img2.acsta.net/r_1280_720/pictures/15/08/20/11/00/228239.jpg' width=140 height=200>",
    "Budget": 20000000,
    "ratingIMDB": 8.1,
    "duration": 128,
    "genre1": "Crime",
    "genre2": "Drama",
    "metacritic": 93,
    "synopsis": "The true story of how the Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese, shaking the entire Catholic Church to its core."
  },
  {
    "Year": 2016,
    "Picture": "Moonlight",
    "Studio": "A24",
    "BoxOffice": 27854932,
    "Nominations": 8,
    "Wins": 3,
    "Release Date": "oct-21",
    "PosterURL": "<img src='https://2.bp.blogspot.com/-gJ-5D2T136E/V64FiYP5b_I/AAAAAAAAjyI/nAn4a3N28lwYUc0bUmJY0w_83ARMzfa7QCLcB/s00/mooNew Line Cinemaight_poster_jposters.jpg' width=140 height=200>",
    "Budget": 4000000,
    "ratingIMDB": 7.4,
    "duration": 111,
    "genre1": "Drama",
    "genre2": "",
    "metacritic": 99,
    "synopsis": "A chronicle of the childhood, adolescence and burgeoning adulthood of a young, African-American, gay man growing up in a rough neighborhood of Miami."
  },
  {
    "Year": 2017,
    "Picture": "The Shape of Water",
    "Studio": "Fox Searchlight",
    "BoxOffice": 61000138,
    "Nominations": 13,
    "Wins": 4,
    "Release Date": "12-ene",
    "PosterURL": "<img src='https://www.filmfetish.com/img/p/2017/07/the-shape-of-water-teaser-poster.jpg' width=140 height=200>",
    "Budget": 19500000,
    "ratingIMDB": 7.5,
    "duration": 123,
    "genre1": "Adventure",
    "genre2": "Drama",
    "metacritic": 87,
    "synopsis": "At a top secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity."
  }
];

var oscarsDatasetMetaData = {
  xField: 'Year',
  yField1: 'BoxOffice',
  yField2: 'Budget',
  xLabelText: 'Year',
  yLabelText: "$",
  yAxisTickFormat: ".2s",
  chartTitleText: "Best Movie Oscar winners Box-Office from 1990",
  tooltipBoxOffice: [
    {
      fieldText: "",
      fieldValue: "Picture"
    },
    {
      fieldText: "Box-Office ($):",
      fieldValue: "BoxOffice"
    }
  ],
  tooltipBudget: [
    {
      fieldText: "",
      fieldValue: "Picture"
    },
    {
      fieldText: "Budget ($):",
      fieldValue: "Budget"
    }
  ],
  information: [
    {
      fieldText: "",
      fieldValue: "Picture"
    },
    {
      fieldText: "",
      fieldValue: "PosterURL"
    },
    {
      fieldText: "Box-Office ($):",
      fieldValue: "BoxOffice"
    },
    {
      fieldText: "Budget ($):",
      fieldValue: "Budget"
    },
    {
      fieldText: "Studio:",
      fieldValue: "Studio"
    },
    {
      fieldText: "Nominations:",
      fieldValue: "Nominations"
    },
    {
      fieldText: "Wins:",
      fieldValue: "Wins"
    },
    {
      fieldText: "Duration (minutes):",
      fieldValue: "duration"
    },
    {
      fieldText: "Genre 1:",
      fieldValue: "genre1"
    },
    {
      fieldText: "Genre 2:",
      fieldValue: "genre2"
    },
    {
      fieldText: "IMDB rating",
      fieldValue: "ratingIMDB"
    },
    {
      fieldText: "Metacritic score (%):",
      fieldValue: "metacritic"
    },
    {
      fieldText: "Synopsis",
      fieldValue: "synopsis"
    }
  ]
};
